apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-backend
  namespace: employee-namespace   # ✅ Replace with your namespace name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-backend
  template:
    metadata:
      labels:
        app: employee-backend
    spec:
      containers:
        - name: employee-backend
          image: IMAGE_PLACEHOLDER  # Change if using Docker Hub/Harbor
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-username-k8s
                  key: DB-USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password-k8s
                  key: DB-PASSWORD
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: db-url-k8s
                  key: DB-URL

            # ✅ NEW: Application Insights connection string
            - name: APPLICATIONINSIGHTS_CONNECTION_STRING
              value: "InstrumentationKey=1f6e828b-06bb-47c0-94c3-986179dc18a5;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/;ApplicationId=a86778e7-f5b8-4bfc-9792-1c77f6a1cf32"

          # ✅ Added resource requests and limits for HPA compatibility
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kv-secrets"