apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: employee-namespace   # ✅ Replace with your namespace name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi