apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: employee-namespace   # ✅ Replace with your namespace name
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "8bf63efc-2ab5-48c8-baa2-1642f4668e57"
    keyvaultName: "employee-kv"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: DB-USERNAME
          objectType: secret      
        - |
          objectName: DB-PASSWORD
          objectType: secret      
        - |
          objectName: DB-URL
          objectType: secret
    tenantId: 9fd93661-9743-4969-b57e-e1f257d6d406
  secretObjects:
    - secretName: db-username-k8s
      type: Opaque
      data:
        - objectName: DB-USERNAME
          key: DB-USERNAME
    - secretName: db-password-k8s
      type: Opaque
      data:
        - objectName: DB-PASSWORD
          key: DB-PASSWORD
    - secretName: db-url-k8s
      type: Opaque
      data:
        - objectName: DB-URL
          key: DB-URL
    - secretName: azure-blob-storage-connection-string-k8s
      type: Opaque
      data:
        - objectName: AZURE-BLOB-STORAGE-CONNECTION-STRING
          key: AZURE-BLOB-STORAGE-CONNECTION-STRING
    - secretName: azure-blob-storage-container-name-k8s
      type: Opaque
      data:
        - objectName: AZURE-BLOB-STORAGE-CONTAINER-NAME
          key: AZURE-BLOB-STORAGE-CONTAINER-NAME