pipeline {
    agent any
    tools {
        maven 'Maven_3'
    }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('employee-docker-token')
        IMAGE_NAME = "learningkarthick/employee-backend"
		 TAG = "${new Date().format('yyyyMMddHHmmss')}"
		  ACR_LOGIN = 'employeeregistryacr.azurecr.io'
    }



    stages {
        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/learningkarthick/Employee_Backend.git',
                    credentialsId: 'employee-token'
            }
        }
        stage('Build with Maven') {
            steps {
                bat 'mvn clean package -DskipTests'
            }
        }
        stage('Build Docker Image') {
            steps {
                bat """
                docker build -t %IMAGE_NAME%:%TAG% -f docker/Dockerfile .
                """
            }
        }
        stage('Login to Docker') {
            steps {
                bat """
                echo %DOCKERHUB_CREDENTIALS_PSW% | docker login -u %DOCKERHUB_CREDENTIALS_USR% --password-stdin
                """
            }
        }
        stage('Push Docker Image') {
            steps {
                bat """
                docker push %IMAGE_NAME%:%TAG%
                """
            }
        }
		stage('Show Tag') {
            steps {
                echo "✅ Docker image pushed as ${IMAGE_NAME}:${TAG}"
            }
        }
         stage('Login to ACR') {
                    steps {
                        withCredentials([usernamePassword(credentialsId: 'employee-azure-registry-token', usernameVariable: 'ACR_USERNAME', passwordVariable: 'ACR_PASSWORD')]) {
                            script {
                                sh "echo $ACR_PASSWORD | docker login $ACR_LOGIN -u $ACR_USERNAME --password-stdin"
                            }
                        }
                    }
                }
                  stage('Push to ACR') {
                            steps {
                                script {
                                    sh "docker push $ACR_LOGIN/myapp:${BUILD_NUMBER}"
                                }
                            }
                        }
    }
}
